### ISSUE TITLE
PR builds failing

### ISSUE THREAD

**Issue by jepler** [adafruit/Adafruit_Learning_System_Guides#1099]
Hi!  I think we need help from an adult here.  I believe I've established that _something_ in the cache is wrong, and this is breaking current PR builds.  I created #1098 because of the failure we saw on #1084.  With no change relative to master branch, the build fails.  With an attempt to address the first error-ish text I saw in the build, nothing changes.  When disabling the travis cache, the build succeeded.

I believe I _could_ use my credentials on travis-ci to clear the cache but I don't want to do this willy-nilly.

**Comment by ladyada** [comment]
i deleted the cache. you can delete them whenever you like.
