### ISSUE TITLE
PWM example uses (slightly) invalid argument

### ISSUE THREAD

**Issue by Andon-A** [adafruit/Adafruit_Learning_System_Guides#1116]
In [CircuitPython_PWM_Piezo.py](https://github.com/adafruit/Adafruit_Learning_System_Guides/blob/master/CircuitPython_Essentials/CircuitPython_PWM_Piezo.py), line 14, it gives the duty_cycle of 65536, when the correct range is 0-65535.

**Comment by ladyada** [comment]
@Andon-A good catch, wanna submit a PR? it would be appreciated :)

**Comment by Andon-A** [comment]
Sure, I have to set up GitHub on this PC anyway, it'll be a good way to make sure everything's set up properly.
