### ISSUE TITLE
Circuit_Playground_Bluefruit_NeoPixel_Controller/NeoPixel_Animator.py needs updating

### ISSUE THREAD

**Issue by dhalbert** [adafruit/Adafruit_Learning_System_Guides#1143]
`Circuit_Playground_Bluefruit_NeoPixel_Controller/NeoPixel_Animator.py` is out of date with respect to the revised `adafruit_led_animation` library. It's used in this guide:

https://learn.adafruit.com/circuit-playground-bluefruit-neopixel-animation-and-color-remote-control/circuitpython-setup-and-code

tagging @kattni @rhooper 

Issue encountered by xtrude64 (discord).

**Comment by kattni** [comment]
Fixed by #1154
