### ISSUE TITLE
Can't run EInk Weather Bonnet example as cron/systemd (fix proposed herein)

### ISSUE THREAD

**Issue by AKAMEDIASYSTEM** [adafruit/Adafruit_Learning_System_Guides#1246]
Hi! I had to make a small change to this [script](https://github.com/adafruit/Adafruit_Learning_System_Guides/blob/master/EInk_Bonnet_Weather_Station/weather.py) to be able to set it up to run continuously through cron or systemd.

I think that the permissions on the folder/file here for the `meteocons.ttf` icon set currently prevent cron use:
https://github.com/adafruit/Adafruit_Learning_System_Guides/blob/00b5088ea7133c6a74089b1b62da426e74d58349/EInk_Bonnet_Weather_Station/weather_graphics.py#L13

I got things working again by making a directory in `/usr/share/fonts/truetype` called `meteocons` and then copying the `meteocons.ttf` file there (and updating the url in the script).

I hope this helps, and thank you for making excellent example code!

AKA

**Comment by makermelissa** [comment]
Thanks, I updated the guide to include this information.
