### ISSUE TITLE
Why does bme280_data_bytes exist?

### ISSUE THREAD

**Issue by loganwedwards** [adafruit/Adafruit_Learning_System_Guides#1281]
https://github.com/adafruit/Adafruit_Learning_System_Guides/blob/ec740ac4eccab0c67f651e9ecdf23148a33d46e6/lorawan_sensing_network/lora_device.py#L79

I think the docs can be clearer here. Does this variable exist solely for debugging or is it meant to be the actual payload.

Currently `rfm9x.send(bme280_data)` is listed.

To be clear, I am happy to make a PR for this, but wanted to fully understand the intended usage.

**Comment by ladyada** [comment]
probably a typo @brentru can look

**Comment by brentru** [comment]
@loganwedwards  Yes, that's a typo - it's meant to be the actual payload in L83. The RFM9x.send() function operates on bytes (https://github.com/adafruit/Adafruit_CircuitPython_RFM9x/blob/master/examples/rfm9x_simpletest.py)

> To be clear, I am happy to make a PR for this, but wanted to fully understand the intended usage.
That'd be great, please tag me.

**Comment by loganwedwards** [comment]
Great. Thanks @ladyada and @brentru !
