### ISSUE TITLE
EZ Make Oven needs updating to latest lib

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_Learning_System_Guides#1439]
Re this thread:
https://forums.adafruit.com/viewtopic.php?f=60&t=174477

Looks like code was written before recent refactoring.

**Comment by ladyada** [comment]
let me try emailing...

**Comment by ladyada** [comment]
@cogliano is going thru the code now

**Comment by ladyada** [comment]
@caternuson a lot got done last nite, have em try the latest code?

**Comment by ladyada** [comment]
closing cause i belive resolved!
