### ISSUE TITLE
PP Tides Graphical memory allocation error

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_Learning_System_Guides#1442]
Re this thread:
https://forums.adafruit.com/viewtopic.php?f=60&t=174180#p852778

I can recreate. Libraries must be bigger now.

**Comment by caternuson** [comment]
yah, i should totally rewrite this to use the newer lib and only use the sub-layers as needed etc.

**Comment by ladyada** [comment]
thanks!
