### ISSUE TITLE
MEmoryError: memory allocation failed

### ISSUE THREAD

**Issue by hifarrer** [adafruit/Adafruit_Learning_System_Guides#1451]
Hello, I made an improvement based no this original code but basically adds the option to have multiple crypto currencies rotating.
The problem is that after an hour the Matrix errors out (Pink flamingo display)
Using MU I was able to debug and see that the allocated memory gets reduced overtime until there is not enough memory in the device so it crashes.
So far I was able to use gc.mem_free() to see available free memory and gc.collect() to free up some memory, doing this extended the time to probably 2 hours but it keeps crashing nonetheless.

I would like the ability to restart the device by using a line of code before it crashes. Is this possible?
I couldn't find any reference to do that.

**Comment by ladyada** [comment]
hihi you can post to the forums or discord with detailed information for help with coding projects!
