### ISSUE TITLE
Update the metrox example to use pwmio

### ISSUE THREAD

**Issue by jepler** [adafruit/Adafruit_Learning_System_Guides#1464]
See #1431 -- https://github.com/adafruit/Adafruit_Learning_System_Guides/blob/master/MetroX_CircuitPython/mib_colorful_light.py needs to updated.

@brentru @dherrada I'll let you work out who should pick this up.

**Comment by ladyada** [comment]
@dherrada wanna take a crack? @brentru is on another big project :)

**Comment by brentru** [comment]
@jepler  I created a PR #1465 since this was originally something I was going to do in https://github.com/adafruit/METROX-CircuitPython/pull/6
