### ISSUE TITLE
Remove max_size and max_glyphs from CircuitPython examples

### ISSUE THREAD

**Issue by lesamouraipourpre** [adafruit/Adafruit_Learning_System_Guides#1603]
The `max_size` parameter on `displayio.Group` is currently ignored and is (hopefully) going to be removed before 7.0.0 final.
The libraries are having this parameter removed from them - https://github.com/adafruit/circuitpython/issues/4959

Edit: I've update the grep to look for `max_glyphs` related to DIsplay_Text Label as well.

This issue is intended as a tracking issue as the Learn Guide code is worked through
`{ grep -r "Group.*max_size" * && grep -r "max_glyphs" * ; } | sed -e "s/\/.*//" | sort | uniq` to give directories
`{ grep -r "Group.*max_size" * && grep -r "max_glyphs" * ; } | grep -v "_JEplayer_" | sort` gives (updated 2021/08/06 14:20 BST)
```
Matrix_On_Air/matrix_on_air.py:    deco_font, color=color[1], text="AIR", max_glyphs=6
Matrix_On_Air/matrix_on_air.py:    deco_font, color=color[3], text="OFF", max_glyphs=6
Matrix_On_Air/matrix_on_air.py:group = displayio.Group(max_size=22)
PyPortal_Calculator/code.py:calc_display = Label(font, text="0", color=BLACK, max_glyphs=MAX_DIGITS)
PyPortal_Calculator/code.py:calc_group = displayio.Group(max_size=25)
PyPortal_Calculator/titano_code.py:calc_display = Label(font, text="0", color=BLACK, max_glyphs=MAX_DIGITS)
PyPortal_Calculator/titano_code.py:calc_group = displayio.Group(max_size=25)
PyPortal_Titano_Weather_Station/openweather_graphics.py:        self.date_text = Label(self.medium_font, max_glyphs=60)
PyPortal_Titano_Weather_Station/openweather_graphics.py:        self.description_text = Label(self.small_font, max_glyphs=60)
PyPortal_Titano_Weather_Station/openweather_graphics.py:                    self.holiday_text = Label(self.medium_font, max_glyphs=60)
PyPortal_Titano_Weather_Station/openweather_graphics.py:        self._icon_group = displayio.Group(max_size=1)
PyPortal_Titano_Weather_Station/openweather_graphics.py:        self.main_text = Label(self.weather_font, max_glyphs=20)
PyPortal_Titano_Weather_Station/openweather_graphics.py:        self.temp_text = Label(self.large_font, max_glyphs=6)
PyPortal_Titano_Weather_Station/openweather_graphics.py:        self._text_group = displayio.Group(max_size=12)
PyPortal_Titano_Weather_Station/openweather_graphics.py:        self.time_text = Label(self.medium_font, max_glyphs=8)
```
If the associated Learn Guide text needs updated I will make a comment on any created PRs. Is there a better way to do this @kattni or @makermelissa ?

- [x] AHT20_OLED - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1605 https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1704
- [x] azure_gfx_helper.py - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1627
- [x] Baudot_TTY - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1607 https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1705
- [x] Buckaroo_Plant_Care_Bot - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1608 https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1717
- [x] Circuit_Playground_Sailor_Moon_Star_Locket - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1609
- [x] CircuitPython_Display_Text - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1612
- [x] CircuitPython_Flying_Toasters - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1614
- [x] CircuitPython_JEplayer_mp3 - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1632
- [x] CircuitPython_Pyloton - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1631
- [x] CircuitPython_PyPaint - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1622
- [x] CircuitPython_RGBMatrix - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1623
- [x] CircuitPython_RPN_Calculator - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1618
- [x] CircuitPython_Scrolling_Clouds - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1614
- [x] CircuitPython_SharpDisplay_Displayio - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1624
- [x] CircuitPython_Sip_and_Puff - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1628
- [x] CircuitPython_Slider - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1629
- [x] CircuitPython_Touch_Deck - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1630
- [x] CircuitStonks - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1706
- [x] CLUE_Altimeter - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1634
- [x] CLUE_BBQ - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1635
- [x] CLUE_Egg_Drop - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1636
- [x] CLUE_Hand_Wash_Timer - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1637
- [x] CLUE_I_Ching - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1638
- [x] CLUE_Light_Painter - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1646
- [x] CLUE_Metal_Detector - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1647
- [x] CLUE_Metronome - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1648
- [x] CLUE_Milk_Checker - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1649
- [x] CLUE_Rock_Paper_Scissors - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1650
- [x] CLUE_Sensor_Plotter - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1651
- [x] Clue_Step_Counter - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1652
- [x] CPB_AMS_Gizmo_BLE - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1653
- [x] CPB_ANCS - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1654
- [x] EInk_CircuitPython_Quickstart - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1655
- [x] FunHouse_IOT_Hub - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1656
- [x] IoT_Party_Parrot - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1657
- [x] I_Voted_Pin - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1658
- [x] LED_Matrix_Scoreboard - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1659
- [x] Macropad_Ableton - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1660
- [x] Macropad_Dragon_Drop - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1695
- [x] Macropad_Hotkeys - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1661
- [x] MagTag_Christmas_Countdown - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1663
- [x] MagTag_Dishwasher_Status - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1665
- [x] MagTag_Goole_Calendar - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1707
- [x] MagTag_NextBus - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1666
- [x] MagTag_Project_Selector - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1667
- [x] MagTag_Tides - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1668
- [x] MagTag_Weather - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1669
- [x] Matrix_On_Air - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1684
- [x] Matrix_Portal_Moon_Clock - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1685
- [x] Matrix_Portal_Tip_Jar - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1686
- [x] Matrix_Sprite_Animation_Player - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1687
- [x] Metro_Matrix_Clock - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1688
- [x] MIDI_CLUE_BLE_Glove - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1689
- [x] MIDI_Melody_Maker - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1690
- [x] Minecraft_Turbopad - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1708
- [x] Minesweep - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1692
- [x] Pico_MIDI_Fighter - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1693
- [x] PyBadge_Blinka_Jump_Game - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1694
- [x] PyBadge_Conference_Badge - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1696
- [x] PyGamer_Improved_Thermal_Camera - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1709
- [x] PyGamer_NeoPixel_Strip_Control - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1697
- [x] PyGamer_Thermal_Camera - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1703
- [x] PyPortal_AWS_IOT_Planter - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1710
- [x] PyPortal_Azure_Plant_Monitor - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1627
- [x] PyPortal_Calculator - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1715
- [x] PyPortal_CircuitPython_2020 - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1716
- [x] PyPortal_Electioncal_US - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1724
- [x] PyPortal_EventCountdown - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1725
- [x] PyPortal_EZ_Make_Oven - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1726
- [x] PyPortal_GCP_IOT_Planter - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1737
- [x] PyPortal_Google_Calendar - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1738
- [x] PyPortal_Halloween_Countdown - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1739
- [x] PyPortal_Hurricane_Tracker - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1740
- [x] PyPortal_IOT_Scale - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1741
- [x] PyPortal_ISS_Tracker - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1742
- [x] PyPortal_LIFX_Controller - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1736
- [x] PyPortal_Mogwai_Clock - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1735
- [x] PyPortal_MQTT_Control - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1734
- [x] PyPortal_OpenWeather - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1733
- [x] pyportal_pet_planter - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1732
- [x] PyPortal_Philips_Hue_Controller - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1731
- [x] PyPortal_Quarantine_Clock - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1730
- [x] PyPortal_Remote - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1729
- [x] PyPortal_Smart_Thermometer - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1728
- [x] PyPortal_Titano_Weather_Station - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1727
- [x] PyPortal_TOTP_Friend - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1714
- [x] PyPortal_Trivia_Time - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1713
- [x] PyPortal_User_Interface - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1712
- [x] PyPortal_UV_Index - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1702
- [x] PyPortal_Wakeup_Light - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1711
- [x] pyportal_weather_station - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1700
- [x] RGB_Matrix_Slot_Machine - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1699
- [x] Say_Their_Names_LEDMatrix - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1698
- [x] Smart_Alarm_Clock - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1683
- [x] TFT_Gizmo_Snowglobe - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1682
- [x] Tilemap_Game_With_CircuitPython - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1681
- [x] Vertical_Garden_Barometer - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1680
- [x] Voice2Json_Edge_Detection - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1679
- [x] Weather_Display_Matrix - https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1678

**Comment by kattni** [comment]
@lesamouraipourpre Unfortunately, this is pretty much the only way to do it. Thank you for making this list! This update needs to be made, and updating the code is a great first step. Not all guides will have associated walk-throughs or text requiring changes, but guarantee that some of them will.

Perhaps @FoamyGuy is up for assisting with this on the Learn guide side of things?

**Comment by lesamouraipourpre** [comment]
Not a problem, I will try to start working through these. A potential issue noticed on @FoamyGuy 's stream on Saturday was that some Learn Guides were written for CircuitPython 3 (and possibly earlier) and may need other changes.

As I don't have the hardware for most of the guides, I will focus on the `max_size` change and try and report any other issues.

**Comment by FoamyGuy** [comment]
I am going to start working on this list from the bottom moving upwards to avoid accidentally duplicating any of @lesamouraipourpre 's work

**Comment by lesamouraipourpre** [comment]
Sounds Good. I'll continue downwards.

**Comment by lesamouraipourpre** [comment]
@FoamyGuy I've modified the `grep` search to look for `max_glyphs` as well - it's added a few more to the list.

**Comment by lesamouraipourpre** [comment]
All current Learn guides have had `max_size` and `max_glyphs` usage removed.

**Comment by ladyada** [comment]
wooohoo! thank you :)
