### ISSUE TITLE
SDlistFiles.ino..adapted to ESP8266 seems not working

### ISSUE THREAD

**Issue by axfatec** [adafruit/Adafruit_Learning_System_Guides#163]
Hello.
I'm not so expert but I did some sketches for ESP8266 using SD.h library.
I would adapt the SDlistFiles.ino and similar SDWebBrowse  sketches found here but in both cases I have the following error compiling with ARDUINO IDE:
error: 'File' does not name a type
 File root;
 ^
Can anyone help me ?   I simply changed the CS pin to  num. 15.
Thanks:
here the adapted sketch:
---------
 /*  SDlistFiles

 */
#include <SPI.h>
#include <SD.h>

File root;

void setup() {
  // Open serial communications and wait for port to open:
  Serial.begin(115200);
  while (!Serial) {
    ; // wait for serial port to connect. Needed for native USB port only
  }

  pinMode(15, OUTPUT);      // set the SS pin as an output (necessary!)
  digitalWrite(15, HIGH);   // but turn off the W5100 chip
  
  Serial.print("Initializing SD card...");

  if (!SD.begin(15)) {
    Serial.println("initialization failed!");
    return;
  }
  Serial.println("initialization done.");

  root = SD.open("/");

  printDirectory(root, 0);

  Serial.println("done!");
}

void loop() {
  // nothing happens after setup finishes.
}

void printDirectory(File dir, int numTabs) {
  while (true) {

    File entry =  dir.openNextFile();
    if (! entry) {
      // no more files
      break;
    }
    for (uint8_t i = 0; i < numTabs; i++) {
      Serial.print('\t');
    }
    Serial.print(entry.name());
    if (entry.isDirectory()) {
      Serial.println("/");
      printDirectory(entry, numTabs + 1);
    } else {
      // files have sizes, directories do not
      Serial.print("\t\t");
      Serial.println(entry.size(), DEC);
    }
    entry.close();
  }
}

**Comment by ladyada** [comment]
hiya this guide was written for Arduino Ethernet shield only. you can try posting in the adafruit forums if you purchased the parts from us.
