### ISSUE TITLE
README.md - Broken link

### ISSUE THREAD

**Issue by OneOfTheInfiniteMonkeys** [adafruit/Adafruit_Learning_System_Guides#1833]
### File
README.md

### Section
"Testing

The code here is partially checked by Travis CI against Pylint (for CircuitPython code) or the Arduino compilation process using travis-ci-arduino."

### Link
"checked by Travis CI"
https://travis-ci.com/adafruit/Adafruit_Learning_System_Guides/

### Issue
Link returns 404 error from travis-ci.com

### Steps to reproduce the error
Select the link "checked by Travis CI"

**Comment by TheKitty** [comment]
Fixing via https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1834
