### ISSUE TITLE
Ukulele code import issue

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_Learning_System_Guides#1999]
Re this thread:
https://forums.adafruit.com/viewtopic.php?f=57&t=187856

From this guide:
https://learn.adafruit.com/light-up-reactive-ukulele/software

The import and instance syntax needs to updated for the LSM6DS33 usage.

```python
from adafruit_lsm6ds import lsm6ds33
```
and
```python
sensor = lsm6ds33.LSM6DS33(i2c)
```

**Comment by ladyada** [comment]
erin's out on mermaid break, can you do the PR?

**Comment by caternuson** [comment]
Sure. Easy changes but no way to test. Going to see if forum poster can test:
https://forums.adafruit.com/viewtopic.php?f=57&t=187856#p910404

**Comment by ladyada** [comment]
good idea!

**Comment by caternuson** [comment]
Closing. The import works now at least.
