### ISSUE TITLE
Update Learning Guide for I2C QT Rotary Encoder re Power Connections

### ISSUE THREAD

**Issue by dnkorte** [adafruit/Adafruit_Learning_System_Guides#2073]
Update the Learning Guide for I2C QT Rotary Encoder ( https://learn.adafruit.com/adafruit-i2c-qt-rotary-encoder/pinouts ) in the Power Pins area to emphasize that hooking up the hard-wired Vin and Ground pins may be required in some situations, even though the i2c stemma cables provide sufficiient power "most of the time".  

RATIONALE: examples in this guide, and most other guides for Stemma-capable boards always demonstrate operation with only the Stemma cables connected.   This suggests that the boards do not NEED hardwired power connections if i2c Stemma cables are used.

SAMPLE SITUATION: i have an application that uses a PyPortal Pynt as processor, powered by 5v from USB and/or from PowerBoost 500C.  The PyPortal is in default condition to supply 5v to i2c connector.  It has CircuitPython 7.1.1 installed.  My application uses 3 of the Rotary Encoder breakouts as indicated above.  They are properly jumpered to live at 0x36, 0x37, 0x38.  Using the standard i2c scanner as shown in ( https://learn.adafruit.com/scanning-i2c-addresses/circuitpython ) to test hookups.  With ONE or TWO rotary encoder breakouts connected (using Stemma cables only - no hardwired power to Vin pins), the scanner properly reports the board addresses.  Any combination of 2 boards works, however as soon as a 3rd board is added the scanner starts reporting every single possible address (0x08 - 0x3f).   (i actually have more than just the 3 indicated and have tried them too, to verify its not a hardware problem on specific boards).   

After hardwiring 5v power supply to the Vin pin on each of the breakouts, the software operates properly.  

I suspect that there is a limited number of boards that may be daisy-chained over i2c before the i2c-provided power is insufficient.  It seems reasonable to suspect that the SAMD09 processor may draw more current than most simple sensors (?) so this issue MIGHT be limited to boards such as this breakout, although i have no way of confirming this.  

My suggestion is to just add a cautionary note to the Power Pins section that suggests hooking up power supply to Vin if unusual behaviour is noticed.

**Comment by kattni** [comment]
Alert added! Thank you for the heads up.
