### ISSUE TITLE
Ble_eval_client.py works on Mac not Windows

### ISSUE THREAD

**Issue by russellchung** [adafruit/Adafruit_Learning_System_Guides#2140]
Hi I am wondering if anyone has similar experience on using the sample BLE_Eval_client.py code using Nordic_UART service.  It is working great for me on Mac Catalina Island but on Window 10, while the BLE adaptor can pair to the Nordic_UART device, but this code keep stuck at "trying to connect".  Any suggestion on how to debug this ?

Thx!

**Comment by TheKitty** [comment]
Best to post on the Adafruit support forum https://forums.adafruit.com/ or the Adafruit Discord https://adafru.it/discord.
