### ISSUE TITLE
REPL spits out errors in the macropad-hotkeys project

### ISSUE THREAD

**Issue by imavroukakis** [adafruit/Adafruit_Learning_System_Guides#2162]
- Arduino board:  Adafruit MacroPad RP2040 
- Arduino IDE version:  N/A using Circuit Python
- List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too):

Using CircuitPython 7.2.5, I am playing around with https://learn.adafruit.com/macropad-hotkeys/project-code . I have noticed that the console spits out a lot of errors when it loads the macros but everything seems to work fine

```
ERROR in ._mac-safari.py
Traceback (most recent call last):
  File "code.py", line 101, in <module>
ImportError: no module named '/macros/'
ERROR in ._media.py
Traceback (most recent call last):
  File "code.py", line 101, in <module>
ImportError: no module named '/macros/'
ERROR in ._numpad.py
Traceback (most recent call last):
  File "code.py", line 101, in <module>
ImportError: no module named '/macros/'
```

**Comment by ladyada** [comment]
you probably didnt Download Bundle to get all the files?
![image](https://user-images.githubusercontent.com/1214161/168656966-6367b213-7b8c-4252-9299-ef298c3d6d27.png)
![image](https://user-images.githubusercontent.com/1214161/168657010-9cc05996-3753-4c33-a424-0dbdb93d794e.png)

**Comment by imavroukakis** [comment]
Sure did!
![image](https://user-images.githubusercontent.com/1764981/168657339-a2455530-26e6-4250-b4be-677b73610c44.png)

**Comment by ladyada** [comment]
._ files are macos 'extras' made by your OS, you could delete them using command line - they're confusing the script but like you said work fine

**Comment by imavroukakis** [comment]
ah thanks, I thought I squashed those when I followed the setup instructions! Apologies for that.

**Comment by ladyada** [comment]
all good! :) if ya want you could submit a PR for the script to ignore files that start with `._` !
