### ISSUE TITLE
CircuitPython_Painter: fix error reporting that currently uses `halt()`

### ISSUE THREAD

**Issue by dhalbert** [adafruit/Adafruit_Learning_System_Guides#23]
`halt()` is used a couple of places to indicate errors, but it doesn't actually exist.

**Comment by dhalbert** [comment]
I'll bet this is supposed to blink D13 at the specified rate.

**Comment by TheKitty** [comment]
Do you want to keep this issue open @dhalbert ?

**Comment by lesamouraipourpre** [comment]
This could probably be closed, `halt` was replaced with `raise OSError` in commit 1cde6aa8894e9f6c5f81ce2beb508a2046aadee6
