### ISSUE TITLE
ESP32s2 reverse tft feather guide doesn't have cap touch section under Circuit Python

### ISSUE THREAD

**Issue by rbrian** [adafruit/Adafruit_Learning_System_Guides#2455]
in the regular esp32s2 feather guide, there is a section under "Circuit Python" for capacitive touch. This page doesn't show in the reverse TFT version. The pins are labelled in the pinout, but there's no info on how to actually use them.

EDIT:  now that I'm reading closer, it's the Circuitpython Essentials group as a whole that's missing.

**Comment by kattni** [comment]
I'm going to close this. Please reply here if you are still having issues with this.
