### ISSUE TITLE
PyPlanter Booting up with root background and temp/moisture icons but doesn't display any data 

### ISSUE THREAD

**Issue by Blacktiger126** [adafruit/Adafruit_Learning_System_Guides#2480]
Hello, I recently built the pyplanter, hooked up all the sensors, downloaded the necessary libraries and ran the project specific code.py file. The pyportal boots up fine, displays the roots background and temperature and moisture icons but does not display the numerical temp and moisture levels. It also times out after a few minutes saying that line 272 is caught in a loop and didn't get data in a timely manner. Can anyone else help with this issue? I have followed every guide exactly and started over multiple times with the same end result.

**Comment by TheKitty** [comment]
Please post your query to forums.adafruit.com for specific help. Thanks.
