### ISSUE TITLE
Project bundle does not include data files

### ISSUE THREAD

**Issue by dhalbert** [adafruit/Adafruit_Learning_System_Guides#2536]
Reported by a user in  https://forums.adafruit.com/viewtopic.php?p=976034#p976034.

The project bundle for the Halloween_Countdown_Matrix does not include the necessary data files. Only the libraries are included.
https://learn.adafruit.com/halloween-countdown-display-matrix/code-the-halloween-countdown

Pinging @tekktrik @jwcooper @kattni @evaherrada @TheKitty. Not sure who might know about this.

Is this what #2499 is referring to?

**Comment by jwcooper** [comment]
I can take a look at this one for learn. I think #2499 may be unrelated, but not 100% on that.
