### ISSUE TITLE
set pylint to 1.92 and undo changes to pylintrc

### ISSUE THREAD

**Issue by ladyada** [adafruit/Adafruit_Learning_System_Guides#254]
hey dan, pylint updated! please tweak travis so it uses 1.9.2 only and revert this commit
https://github.com/adafruit/Adafruit_Learning_System_Guides/commit/6fc1cd11a3ac795329b3dd7a583d495ba9942012
(i disabled consider-swap-variables)

**Comment by dhalbert** [comment]
Fixed by #255.
