### ISSUE TITLE
The link to lindustrial pack by oberza is broken

### ISSUE THREAD

**Issue by ggsato** [adafruit/Adafruit_Learning_System_Guides#2715]
The link in the following warning of [Next Level MakeCode Arcade](https://learn.adafruit.com/next-level-makecode-arcade-games/asset-tool) is broken.

> For this background art, I adapted some of the excellent designs of OllieBerzs' Industrial Pack assets found here https://ollieberzs.itch.io/industrial-pack You can name your own price and use them in personal and commercial projects.

The correct link seems to be this one.
https://oberzs.itch.io/industrial-pack

I will make a PR.

**Comment by ggsato** [comment]
I can't find the guide [Next Level MakeCode Arcade Games](https://learn.adafruit.com/next-level-makecode-arcade-games) in this repository. Doesn't this belong to this one?

**Comment by TheKitty** [comment]
You can report broken links via the Feedback  link in any guide. https://learn.adafruit.com/feedback/new?page_id=16161

**Comment by ggsato** [comment]
@TheKitty Thanks, done!

**Comment by jedgarpark** [comment]
I updated the guide with the new link, thanks @ggsato !

**Comment by ggsato** [comment]
@jedgarpark Confirmed. Thanks for your awesome guides!

**Comment by jedgarpark** [comment]
@ggsato I appreciate it, you're very welcome!
