### ISSUE TITLE
50 or 10.0

### ISSUE THREAD

**Issue by gpabdo** [adafruit/Adafruit_Learning_System_Guides#302]
I could be totally wrong, but should this be labeled `10.0um / 0.1L air` and not `50 um / 0.1L air`?

https://github.com/adafruit/Adafruit_Learning_System_Guides/blob/b410abf010afc35fa8fd7afa7881d3b1795471d1/PMS5003_Air_Quality_Sensor/PMS5003_Arduino/PMS5003_Arduino.ino#L50

"Particulate matter per 0.1L air, categorized into 0.3um, 0.5um, 1.0um, 2.5um, 5.0um and **10um** size bins"

**Comment by ladyada** [comment]
good catch! fixed :)
