### ISSUE TITLE
Dotstar examples have MOSI and SCK reversed

### ISSUE THREAD

**Issue by ATMakersBill** [adafruit/Adafruit_Learning_System_Guides#327]
Hi all, 

I was working from an example from the Learning System and found an error in the sample code.  Turns out I see it once in the forums as well (but I don't know how to report that).  To be honest, I don't remember copying in this code (but I must have, unless some Trinkets shipped with code that includes this error)

Here's the Tutorial for the Mini Pinball Table with Gemma M0: 
https://learn.adafruit.com/mini-pinball-table-with-gemma-m0/code-the-gemma-m0-with-circuitpython

And here is sample code in the Forums
https://forums.adafruit.com/viewtopic.php?f=47&t=131600

```
#set up on board DotStar
pixel = dotstar.DotStar(APA102_MOSI, APA102_SCK, 1, brightness=0.1)
pixel.fill([50, 0, 0]) #color in g - b - r color order
pixel.show()
```

Note that MOSI and SCK are reversed in this.  It leads to bizarre behavior including RGB swapping and general madness

**Comment by jedgarpark** [comment]
Thanks, fixed it now.
