### ISSUE TITLE
CircuitPython_Painter - About project files

### ISSUE THREAD

**Issue by mesutburan** [adafruit/Adafruit_Learning_System_Guides#33]
Hi,
Will you share the following files with me?
mail : [redacted]

import board
import digitalio
import time
import gc
import busio

**Comment by dhalbert** [comment]
These modules are built in to CircuitPython - they are not separate Python files you can view.

**Comment by mesutburan** [comment]
Can I do this project with raspberry pi?
Thanks.

**Comment by dhalbert** [comment]
See this project: https://learn.adafruit.com/dotstar-pi-painter/raspberry-pi-setup, which uses a C library that's called from Python on RPi.

A better place to ask support questions like this is https://forums.adafruit.com. We use GitHub for code bugs and enhancements, but not for general project support. Thanks.
