### ISSUE TITLE
All_Seeing_Skull missing conversion tool

### ISSUE THREAD

**Issue by combs** [adafruit/Adafruit_Learning_System_Guides#351]
All_Seeing_Skull/README.md says:

```
Folder 'convert' contains Python sketch for generating graphics header files. Requires Python Imaging Library. Example images are also in this directory.
```

but these files are not in the repository.

**Comment by jedgarpark** [comment]
thanks. I'm removing the reference to this in the readme, as those scripts are in the uncanny eye repo

**Comment by combs** [comment]
Here's a link for future visitors to this issue. https://github.com/adafruit/Uncanny_Eyes
