### ISSUE TITLE
Rack Pinion Project - Invalid f3d and step files

### ISSUE THREAD

**Issue by basktrading** [adafruit/Adafruit_Learning_System_Guides#527]
Hi, it seems that the source f3d and step files in the Rack Pinion Project are invalid, can you please check? Thanks!

**Comment by djecken** [comment]
Sure, I download from the repo and uploaded to latest version of Fusion 360. Both files check out. Is there a specific error? Try using "Save Link As" option when left-clicking download button.

**Comment by basktrading** [comment]
Thanks for your quick response ,,  you are correct, my bad. Relatively new to github and I wasn't correctly 
downloading the file as I usually would using right click on link, then save as. Sorry for the bother, have a super weekend!

**Comment by webseed50** [comment]
Where can i download the rack and pinion f3d file?

**Comment by djecken** [comment]
@webseed50 try downloading from the github repo or thingiverse. github link: https://github.com/adafruit/Adafruit_Learning_System_Guides/tree/master/Rack_Pinion_Bot/source thingiverse link: https://www.thingiverse.com/thing:3038784/files
