### ISSUE TITLE
PyPortal demos need changes for displayio TileGrid

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/Adafruit_Learning_System_Guides#567]
The PyPortal_Openweather and pyportal_weather_station guides use TileGrid and have the "old" position kwarg. This was updated in displayio to take x,y kwargs instead.

Should they be fixed with try/except on TypeError to for "backward compatibility" of just updated for the latest version of displayio?

**Comment by ladyada** [comment]
please update to try/except

**Comment by jerryneedell** [comment]
submitted PR #568

**Comment by ladyada** [comment]
thanks - is this ready to close ... or more needed?

**Comment by jerryneedell** [comment]
It's all that I know of. We can re-opne if more turn up
