### ISSUE TITLE
alarm clock snooze crash

### ISSUE THREAD

**Issue by djecken** [adafruit/Adafruit_Learning_System_Guides#579]
@dastels Pressing the snooze button while in clock is in"snoozing mode" causes the code to crash. Also happens when going into the settings page while the clock is snoozing.

![snooze-crash](https://user-images.githubusercontent.com/869133/54933378-ec98cd80-4ef2-11e9-85d9-e1f415bd885d.jpg)

**Comment by djecken** [comment]
@dastels tested latest code. getting there! 

- the runtime error occurs on the 4th snooze event.
- after the alarm background loads the sound is delayed by 3-secs.

**Comment by dastels** [comment]
Ok, I’ll look into the error. Same as before? The sound delay is just how the timing is done. I’ll change that.

Dave

**Comment by djecken** [comment]
yea same "group full" type. Think it would sound nice to play this 10sec looping song. 
[song-mix.zip](https://github.com/adafruit/Adafruit_Learning_System_Guides/files/3006019/song-mix.zip)

**Comment by dastels** [comment]
Fix is being tested... I'm at 7 or 8 snooze events and it's solid.
I've changed the alarm sound playing so that it plays "alarm.wav" so you can drop in whatever file you want. The file you provided played a couple seconds and started just ticking (on the PyPortal).  It played fine in Linux.
FYI I'm using 4.0 beta 3 and 5 (and head) still are too buggy.

**Comment by djecken** [comment]
nice! i'm using 4.0 beta 5 as well. I also tested the audio file and got similar "clicking" behavior.

**Comment by dastels** [comment]
My phrasing was ambiguous. I'm using Beat 3. I tried Beta 5 and found it not stable enough. I'm using the latest (yesterday) bundle release, though.

**Comment by dastels** [comment]
Updated PR. I went through a dozen or so snooze events without any issues.

**Comment by djecken** [comment]
switched over to beta 3 and still getting a "clicking" noise with the 10-sec wav file. any suggestions? snooze seems solid now.

**Comment by djecken** [comment]
OK I trimmed the wav file down to ~2seconds and reduced to 22.05kHz and still getting clicks - it won't play the whole sound.

**Comment by djecken** [comment]
OK trying a different audio file. this time it's a wav 16-bit interger, 16kHz, mono. Doesn't play more than a 1/4 sec of the sound followed by the clicking. 
[alarm.zip](https://github.com/adafruit/Adafruit_Learning_System_Guides/files/3008730/alarm.zip)

**Comment by djecken** [comment]
@dastels can you download the newer audio file and test to see if the issues persists? thanks!

**Comment by dastels** [comment]
"Blip.. tick tick tick"

**Comment by djecken** [comment]
Ahh hrmmm. I've tried three different audio files now and can't get any of them to work like the original alarm sound you have. Any suggestions?

**Comment by dastels** [comment]
This last one has the same sample rate & bitrate as the original I used, so I'm stumped by it. Duration and file size almost the same..

I reconverted/exported it and get the same thing "blip tick tick tick"

**Comment by djecken** [comment]
strange! i wonder if this could this be a caching issue?

**Comment by dastels** [comment]
I'm not familiar enough with the sound player internals to say.

**Comment by ladyada** [comment]
hiya folkx is this resolved?
