### ISSUE TITLE
Missing file in PyPortal_ArduinoSelfTest

### ISSUE THREAD

**Issue by dfdy** [adafruit/Adafruit_Learning_System_Guides#724]
When I try to compile and upload the PyPortal Arduino Self Test I get the following error:

`Adafruit_QSPI_GD25Q.h: No such file or directory`

I can't find this file on GitHub, and it no longer seems to be part of the QSPI library.

**Comment by ladyada** [comment]
@brentru ahh this got changed, since you're going to bring up the mini, wanna fix this too?

**Comment by brentru** [comment]
Sounds good, I’ll test and fix when I bring up the mini.

**Comment by brentru** [comment]
@dfdy  This was fixed in PR 725, merged into master. Try it out and make sure you have the latest Adafruit QSPI library (3.0.0) installed.

https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/725
