### ISSUE TITLE
Unable to change pad threshold

### ISSUE THREAD

**Issue by novakoda** [adafruit/Adafruit_Learning_System_Guides#733]
Hello Im trying using the Circuit Playground Express with the cpx-expressive-midi-controller v1.2 code and when using alligator clips attached to objects, sometimes the notes are being played before my hand actually touches the object. 

I've tried changing 
`keydown = [False] * 10`
to 
`keydown = [False] * 5`
and 20, 15, 1, etc. but nothing really has an effect.

I'm not sure if I'm doing something wrong or if this is not possible with the code?

Thanks in advance for any help.

**Comment by tannewt** [comment]
Hi, we usually do technical support on the Adafruit forums here: https://forums.adafruit.com/

The touch code should auto calibrate. To change it you'll need to add code after here: https://github.com/adafruit/Adafruit_Learning_System_Guides/blob/master/Circuit_Playground_Express_USB_MIDI/cpx-expressive-midi-controller.py#L115

The code after can set the threshold property to change the sensitivity. More info on it here: https://circuitpython.readthedocs.io/en/4.x/shared-bindings/touchio/TouchIn.html#touchio.TouchIn.threshold
