### ISSUE TITLE
Bad pin name in guide for Digital Pot

### ISSUE THREAD

**Issue by ATMakersBill** [adafruit/Adafruit_Learning_System_Guides#808]
In the new Digital Pot Stemma QT board, the pinout section refers to "Vb" when the silkscreen names it "V+" (like the datasheet.  While Vb (bias voltage) makes sense, it's not what's on the board :-)

https://learn.adafruit.com/ds3502-i2c-potentiometer/pinouts?fbclid=IwAR2UlugzHcY_LPTtroxBM4e2nQTgkbMjrIy8K57lE2WUVAeZpyeiRbcPLes#resistor-pins-2-4

**Comment by siddacious** [comment]
Fixed, thanks @ATMakersBill !
