### ISSUE TITLE
Slideshow Soundtrack Error

### ISSUE THREAD

**Issue by djecken** [adafruit/Adafruit_Learning_System_Guides#846]
Testing **slideshows_slideshow.py** code for the TinyMuseumTour Learn guide on HalloWing M4 running Circuit Python 5 Alpha 4. REPL throws error:

`code.py output:
Traceback (most recent call last):
  File "code.py", line 7, in <module>
  File "adafruit_slideshow.py", line 200, in __init__
  File "adafruit_slideshow.py", line 323, in advance
AttributeError: 'Display' object has no attribute 'wait_for_frame'`

Learn guide:
https://learn.adafruit.com/tiny-museum-tour-device/code-with-circuitpython

github code:
https://github.com/adafruit/Adafruit_Learning_System_Guides/blob/master/Slideshows_Soundtrack/slideshows_soundtrack.py

**Comment by ladyada** [comment]
@makermelissa see https://github.com/adafruit/Adafruit_CircuitPython_Slideshow/commits/master

**Comment by makermelissa** [comment]
Odd, my error is:
```
Traceback (most recent call last):
  File "code.py", line 10, in <module>
AttributeError: 'module' object has no attribute 'TOUCH1'
```
I did a dir(board) and got:
```
>>> import board
>>> dir(board)
['__class__', 'A0', 'A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'A9', 'ACCELEROMETER_INTERRUPT', 'BATTERY', 'CAP_PIN', 'D0', 'D1', 'D10', 'D11', 'D12', 'D13', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'D8', 'D9', 'DISPLAY', 'EXTERNAL_NEOPIXEL', 'I2C', 'LIGHT', 'MISO', 'MOSI', 'NEOPIXEL', 'RX', 'SCK', 'SCL', 'SDA', 'SENSE', 'SPEAKER_ENABLE', 'SPI', 'TX', 'UART', 'VOLTAGE_MONITOR']
```
So it's not seeing the touch pads for some reason. This was with CP 5.0 Alpha 4 that I downloaded off of circuitpython.org.

**Comment by makermelissa** [comment]
Also, I couldn't find any calls to `wait_for_frame()` in the latest Adafruit_CircuitPython_Slideshow.

**Comment by makermelissa** [comment]
Some more info. It works fine on HalloWing M0. On HallWing M4, it shows the first image briefly before giving the TOUCH1 error and it's small and in the upper left corner (resolution difference).

**Comment by makermelissa** [comment]
Ok, I changed board.TOUCH1 to board.A5 and board.TOUCH4 to board.A2 as labeled on the board. Now this is the error I get:
```
Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.
code.py output:
Traceback (most recent call last):
  File "code.py", line 10, in <module>
ValueError: No pulldown on pin; 1Mohm recommended
```

**Comment by ladyada** [comment]
@djecken plz try!

**Comment by djecken** [comment]
confirmed works on HalloWing M4 running circuit python 5 alpha 4
