### ISSUE TITLE
HalloWing Jump Sound Errors

### ISSUE THREAD

**Issue by djecken** [adafruit/Adafruit_Learning_System_Guides#847]
Testing code with HalloWing M4 running Circuit Python 5 alpha 4. 

Link to code:
https://github.com/adafruit/Adafruit_Learning_System_Guides/tree/master/Hallowing_Jump_Sound

Link to guide:
https://learn.adafruit.com/last-minute-halloween-accoutrements-with-hallowing/sound-costume

REPL throws following error:

`code.py output:
Traceback (most recent call last):
  File "code.py", line 43, in <module>
ValueError: No pulldown on pin; 1Mohm recommended`

**Comment by ladyada** [comment]
pleaset test it on a hallowing m0 to verify it still works there

**Comment by djecken** [comment]
tested code with HalloWing M0 running circuit python 5 alpha 4. Error from REPL

`code.py output:
Traceback (most recent call last):
  File "code.py", line 43, in <module>
ValueError: TFT_BACKLIGHT in use`

**Comment by djecken** [comment]
getting very similar error on circuit python 4.1.0 stable 

`Traceback (most recent call last):
  File "code.py", line 43, in <module>
ValueError: TFT_BACKLIGHT in use`

**Comment by ladyada** [comment]
@makermelissa will check this out next!

**Comment by makermelissa** [comment]
Got the TFT backlight working, but the plot thickens. We have a LIS3DH on the M0 and an MSA301 on the M4 according to the schematic.
