### ISSUE TITLE
 SerialESPPassthrough.ino - neopixel updates interfering with Serial communication on Teensy

### ISSUE THREAD

**Issue by embedded-creations** [adafruit/Adafruit_Learning_System_Guides#876]
I'm trying this sketch with several Teensys: LC, 4.0, 3.5, and found it couldn't even forward the message the ESP32 prints out after resetting to boot mode without dropping characters.  Attempting programming with `ESPTool.py` would fail as it couldn't even get past trying to connect.

If I comment out the `pixel*` calls in `loop()`, it works without dropping characters, and programming flash (at least on 3.5 and LC, Teensy 4.0 still has an issue, but it seems unrelated)

Arduino 1.8.9
Teensyduino 1.4.7
Adafruit_Neopixel 1.2.5

**Comment by ladyada** [comment]
huh weird! ok please submit a PR, you can move the LED blinkin' outside the loop

**Comment by ladyada** [comment]
closing as no PR was submitted
