### ISSUE TITLE
M4_eyes voice not working on Monster Mask

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/Adafruit_Learning_System_Guides#879]
I just tried M4_eyes on Monster mask from the updated Learning Guide and "voice" seems to be broken. If I enable it, I just get blank screens, nothing..  Without voice, everything is working fine. Is this a known issue?
I tried this example: https://learn.adafruit.com/adafruit-monster-m4sk-eyes/voice-changer-2#example-config-dot-eye-file-14-8 
as well as just adding voice : true  to other working "eyes"
In both cases, it just seems to hang during the start-up

**Comment by ladyada** [comment]
what if ya try the UF2?

**Comment by jerryneedell** [comment]
which .uf2?  the default does not have voice enabled.

**Comment by jerryneedell** [comment]
ahh -- never mind -- that is a coffin parameter -- will try it

**Comment by jerryneedell** [comment]
Is the UF2 from the latest repo -- it used to work

**Comment by ladyada** [comment]
https://learn.adafruit.com/adafruit-monster-m4sk-eyes/m-eyes-firmware this Uf2

**Comment by jerryneedell** [comment]
yes -- it works -- was it built from the latest repo ?

**Comment by ladyada** [comment]
no, repo is undergoing some work - could be something missing.

**Comment by jerryneedell** [comment]
OK -- thanks -- I'll wait for updates and take a closer look at the code.

**Comment by jerryneedell** [comment]
it is working with the latest code ( with Adafruit_ZeroPDM) - tested on 10/220/2019
