### ISSUE TITLE
Compile errors using example code

### ISSUE THREAD

**Issue by joeynuggetz** [adafruit/Adafruit_Learning_System_Guides#889]
I'm using a Huzzah  ESP8266 Feather and I'm trying to compile the code provided here: 
https://learn.adafruit.com/feather-weather-lamp/software

Getting below errors. 

c:/users/joe/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-3-20ed2b9/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: sketch\buttoncycler.ino.cpp.o:(.text.setup+0x28): undefined reference to `animConfig(unsigned short, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char)'

c:/users/joe/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-3-20ed2b9/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: sketch\buttoncycler.ino.cpp.o:(.text.setup+0x2c): undefined reference to `animSetup()'

c:/users/joe/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-3-20ed2b9/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: sketch\buttoncycler.ino.cpp.o: in function `setup':

C:\Users\Joe\AppData\Local\Temp\arduino_modified_sketch_128265/buttoncycler.ino:38: undefined reference to `animConfig(unsigned short, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char)'

c:/users/joe/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-3-20ed2b9/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: C:\Users\Joe\AppData\Local\Temp\arduino_modified_sketch_128265/buttoncycler.ino:36: undefined reference to `animSetup()'

c:/users/joe/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-3-20ed2b9/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: sketch\buttoncycler.ino.cpp.o: in function `updateWeather()':

C:\Users\Joe\AppData\Local\Temp\arduino_modified_sketch_128265/buttoncycler.ino:96: undefined reference to `animConfig(unsigned short, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char)'

c:/users/joe/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-3-20ed2b9/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: C:\Users\Joe\AppData\Local\Temp\arduino_modified_sketch_128265/buttoncycler.ino:99: undefined reference to `animConfig(unsigned short, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char)'

c:/users/joe/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-3-20ed2b9/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: C:\Users\Joe\AppData\Local\Temp\arduino_modified_sketch_128265/buttoncycler.ino:101: undefined reference to `animConfig(unsigned short, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char)'

Multiple libraries were found for "ESP8266WiFi.h"
 Used: C:\Users\Joe\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.1\libraries\ESP8266WiFi
c:/users/joe/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-3-20ed2b9/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: C:\Users\Joe\AppData\Local\Temp\arduino_modified_sketch_128265/buttoncycler.ino:101: undefined reference to `animConfig(unsigned short, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char)'

c:/users/joe/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-3-20ed2b9/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: C:\Users\Joe\AppData\Local\Temp\arduino_modified_sketch_128265/buttoncycler.ino:102: undefined reference to `animConfig(unsigned short, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char)'

c:/users/joe/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-3-20ed2b9/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: sketch\buttoncycler.ino.cpp.o:C:\Users\Joe\AppData\Local\Temp\arduino_modified_sketch_128265/buttoncycler.ino:105: more undefined references to `animConfig(unsigned short, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char)' follow

c:/users/joe/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-3-20ed2b9/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: sketch\buttoncycler.ino.cpp.o: in function `updateWeather()':

C:\Users\Joe\AppData\Local\Temp\arduino_modified_sketch_128265/buttoncycler.ino:160: undefined reference to `waitForFrame()'

c:/users/joe/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-3-20ed2b9/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: C:\Users\Joe\AppData\Local\Temp\arduino_modified_sketch_128265/buttoncycler.ino:163: undefined reference to `renderFrame()'

c:/users/joe/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-3-20ed2b9/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: sketch\buttoncycler.ino.cpp.o: in function `loop':

C:\Users\Joe\AppData\Local\Temp\arduino_modified_sketch_128265/buttoncycler.ino:166: undefined reference to `waitForFrame()'

c:/users/joe/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-3-20ed2b9/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: C:\Users\Joe\AppData\Local\Temp\arduino_modified_sketch_128265/buttoncycler.ino:169: undefined reference to `renderFrame()'

collect2.exe: error: ld returned 1 exit status

exit status 1
Error compiling for board Adafruit Feather HUZZAH ESP8266.

**Comment by ladyada** [comment]
download all files
https://github.com/adafruit/Adafruit_Learning_System_Guides/tree/master/ESP8266_Weather_Pixels/WeatherPixels
