### ISSUE TITLE
Dead link in Weather Pixels

### ISSUE THREAD

**Issue by joeynuggetz** [adafruit/Adafruit_Learning_System_Guides#890]
Code links to query.yahooapis.com which doesn't exist anymore.

**Comment by ladyada** [comment]
please be specific where exactly you see a broken link - thanx

**Comment by joeynuggetz** [comment]
Line 17 

https://github.com/adafruit/Adafruit_Learning_System_Guides/blob/master/ESP8266_Weather_Pixels/WeatherPixels/weatherPixels.ino

**Comment by ladyada** [comment]
ok sounds like the code is not going to work anymore 
@TheKitty please deprecate the guide https://learn.adafruit.com/feather-weather-lamp

**Comment by joeynuggetz** [comment]
Darn, looked cool.

**Comment by ladyada** [comment]
if you find an alternative solution to the code please submit a PR, thanks!

**Comment by TheKitty** [comment]
@ladyada - the guide has now been marked as deprecated and a red warning placed that the code no longer works due to the yahoo change.
