### ISSUE TITLE
PyPortal_Smart_Thermometer fails in displayio with CP 5.0-alpha

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/Adafruit_Learning_System_Guides#891]
This fails for CP5.0-alpha.  It works for CP 4.1.0

```
Press any key to enter the REPL. Use CTRL-D to reload.
Adafruit CircuitPython 5.0.0-alpha.4-167-g0ccab508f on 2019-10-11; Adafruit PyPortal with samd51j20
>>> import thermometer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "thermometer.py", line 59, in <module>
  File "thermometer_helper.py", line 33, in __init__
ValueError: Group already used
>>> 

```

clearly something changed in displayio, but I am having trouble finding it.
I suspect there are other similar issues in the guides...

**Comment by ladyada** [comment]
jerry, can you try narrowing the error to an example that we can easily repro for analysis? it would be super helpful!

**Comment by jerryneedell** [comment]
Sure -- I'm trying to do that, not as easy as I'd hoped. I'll post it when I have something.

**Comment by jerryneedell** [comment]
Yay! fixed -- PR soon after  bit more testing. Thanks @tannewt
