### ISSUE TITLE
SIM800L Breakout Module

### ISSUE THREAD

**Issue by Dancopy** [adafruit/Adafruit_Learning_System_Guides#900]
What must be changed in the sketch to use the GSM SIM800L Breakout module, like this: https://www.ebay.com/itm/SIM800L-V2-0-5V-GPRS-GSM-TTL-Port-LGA-Chip-Quadband-L-Shape-Antenna-for-Arduino/332800310271?var=541920377421
and TFT Display ILI9341 SPI Breakout?
Thanks

**Comment by ladyada** [comment]
please contact the ebay seller for tech support
