### ISSUE TITLE
TFT Gizmo Snow Globe

### ISSUE THREAD

**Issue by djecken** [adafruit/Adafruit_Learning_System_Guides#913]
Testing out **snowglobe_fancy.py** code with Adafruit CircuitPython 5.0.0-alpha.4 on 2019-09-15; Adafruit Circuit Playground Bluefruit with nRF52840. Using library bundle adafruit-circuitpython-bundle-5.x-mpy-20191024

Error from REPL:

`code.py output:
Traceback (most recent call last):
  File "code.py", line 51, in <module>
ValueError: color buffer must be 3 bytes (RGB) or 4 bytes (RGB + pad byte)`

the **snowglobe_simple.py** code runs fine, no errors.

link to code: 
https://github.com/adafruit/Adafruit_Learning_System_Guides/tree/master/TFT_Gizmo_Snowglobe

**Comment by djecken** [comment]
maybe because the bitmaps are missing?

**Comment by makermelissa** [comment]
Looks like if the bitmap is missing, it's trying to load the filename into a property that expects a number.

**Comment by djecken** [comment]
@makermelissa yep, looks like it. @caternuson hiya, feel free to add those bitmaps when ya can :-)

**Comment by caternuson** [comment]
Yep. Just code here. I'll add the bitmaps to the guide.

I tested that behavior and it seemed to be fault tolerant - like it was able to cast the string to an int and at least have some kind of color background. Let me look at that again.... :/

**Comment by djecken** [comment]
works nicely!

**Comment by caternuson** [comment]
cool. thanks. sorry about that.
